version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/api_ecommerce
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: api_ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
